//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBibliotecaService")]
    public interface IBibliotecaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarLivroResponse")]
        void CadastrarLivro(ClassesBasicas.Livro.LivroBC l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarLivroResponse")]
        System.Threading.Tasks.Task CadastrarLivroAsync(ClassesBasicas.Livro.LivroBC l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarLivroResponse")]
        void AlterarLivro(ClassesBasicas.Livro.LivroBC l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarLivroResponse")]
        System.Threading.Tasks.Task AlterarLivroAsync(ClassesBasicas.Livro.LivroBC l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/ListarLivroResponse")]
        ClassesBasicas.Livro.LivroBC[] ListarLivro(ClassesBasicas.Livro.LivroBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/ListarLivroResponse")]
        System.Threading.Tasks.Task<ClassesBasicas.Livro.LivroBC[]> ListarLivroAsync(ClassesBasicas.Livro.LivroBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeletarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/DeletarLivroResponse")]
        void DeletarLivro(ClassesBasicas.Livro.LivroBC l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeletarLivro", ReplyAction="http://tempuri.org/IBibliotecaService/DeletarLivroResponse")]
        System.Threading.Tasks.Task DeletarLivroAsync(ClassesBasicas.Livro.LivroBC l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarUsuarioResponse")]
        void CadastrarUsuario(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarUsuarioResponse")]
        System.Threading.Tasks.Task CadastrarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarUsuarioResponse")]
        void AlterarUsuario(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarUsuarioResponse")]
        System.Threading.Tasks.Task AlterarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/ListarUsuarioResponse")]
        ClassesBasicas.Usuario.UsuarioBC[] ListarUsuario(ClassesBasicas.Usuario.UsuarioBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<ClassesBasicas.Usuario.UsuarioBC[]> ListarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeletarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/DeletarUsuarioResponse")]
        void DeletarUsuario(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeletarUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/DeletarUsuarioResponse")]
        System.Threading.Tasks.Task DeletarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarAluguelResponse")]
        void CadastrarAluguel(ClassesBasicas.Aluguel.AluguelBC a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarAluguelResponse")]
        System.Threading.Tasks.Task CadastrarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarAluguelResponse")]
        void AlterarAluguel(ClassesBasicas.Aluguel.AluguelBC a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarAluguelResponse")]
        System.Threading.Tasks.Task AlterarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/ListarAluguelResponse")]
        ClassesBasicas.Aluguel.AluguelBC[] ListarAluguel(ClassesBasicas.Aluguel.AluguelBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/ListarAluguelResponse")]
        System.Threading.Tasks.Task<ClassesBasicas.Aluguel.AluguelBC[]> ListarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeltetarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/DeltetarAluguelResponse")]
        void DeltetarAluguel(ClassesBasicas.Aluguel.AluguelBC a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeltetarAluguel", ReplyAction="http://tempuri.org/IBibliotecaService/DeltetarAluguelResponse")]
        System.Threading.Tasks.Task DeltetarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarPagamentoResponse")]
        void CadastrarPagamento(ClassesBasicas.Pagamento.PagamentoBC p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/CadastrarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/CadastrarPagamentoResponse")]
        System.Threading.Tasks.Task CadastrarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarPagamentoResponse")]
        void AlterarPagamento(ClassesBasicas.Pagamento.PagamentoBC p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/AlterarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/AlterarPagamentoResponse")]
        System.Threading.Tasks.Task AlterarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/ListarPagamentoResponse")]
        ClassesBasicas.Pagamento.PagamentoBC[] ListarPagamento(ClassesBasicas.Pagamento.PagamentoBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/ListarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/ListarPagamentoResponse")]
        System.Threading.Tasks.Task<ClassesBasicas.Pagamento.PagamentoBC[]> ListarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeletarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/DeletarPagamentoResponse")]
        void DeletarPagamento(ClassesBasicas.Pagamento.PagamentoBC p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/DeletarPagamento", ReplyAction="http://tempuri.org/IBibliotecaService/DeletarPagamentoResponse")]
        System.Threading.Tasks.Task DeletarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/LancarMulta", ReplyAction="http://tempuri.org/IBibliotecaService/LancarMultaResponse")]
        void LancarMulta(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/LancarMulta", ReplyAction="http://tempuri.org/IBibliotecaService/LancarMultaResponse")]
        System.Threading.Tasks.Task LancarMultaAsync(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/BaixaMulta", ReplyAction="http://tempuri.org/IBibliotecaService/BaixaMultaResponse")]
        void BaixaMulta(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/BaixaMulta", ReplyAction="http://tempuri.org/IBibliotecaService/BaixaMultaResponse")]
        System.Threading.Tasks.Task BaixaMultaAsync(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/EmitirNF", ReplyAction="http://tempuri.org/IBibliotecaService/EmitirNFResponse")]
        void EmitirNF(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/EmitirNF", ReplyAction="http://tempuri.org/IBibliotecaService/EmitirNFResponse")]
        System.Threading.Tasks.Task EmitirNFAsync(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/BloquearUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/BloquearUsuarioResponse")]
        void BloquearUsuario(ClassesBasicas.Usuario.UsuarioBC u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/BloquearUsuario", ReplyAction="http://tempuri.org/IBibliotecaService/BloquearUsuarioResponse")]
        System.Threading.Tasks.Task BloquearUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBibliotecaServiceChannel : ConsoleApp1.ServiceReference1.IBibliotecaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BibliotecaServiceClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.IBibliotecaService>, ConsoleApp1.ServiceReference1.IBibliotecaService {
        
        public BibliotecaServiceClient() {
        }
        
        public BibliotecaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BibliotecaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CadastrarLivro(ClassesBasicas.Livro.LivroBC l) {
            base.Channel.CadastrarLivro(l);
        }
        
        public System.Threading.Tasks.Task CadastrarLivroAsync(ClassesBasicas.Livro.LivroBC l) {
            return base.Channel.CadastrarLivroAsync(l);
        }
        
        public void AlterarLivro(ClassesBasicas.Livro.LivroBC l) {
            base.Channel.AlterarLivro(l);
        }
        
        public System.Threading.Tasks.Task AlterarLivroAsync(ClassesBasicas.Livro.LivroBC l) {
            return base.Channel.AlterarLivroAsync(l);
        }
        
        public ClassesBasicas.Livro.LivroBC[] ListarLivro(ClassesBasicas.Livro.LivroBC filtro) {
            return base.Channel.ListarLivro(filtro);
        }
        
        public System.Threading.Tasks.Task<ClassesBasicas.Livro.LivroBC[]> ListarLivroAsync(ClassesBasicas.Livro.LivroBC filtro) {
            return base.Channel.ListarLivroAsync(filtro);
        }
        
        public void DeletarLivro(ClassesBasicas.Livro.LivroBC l) {
            base.Channel.DeletarLivro(l);
        }
        
        public System.Threading.Tasks.Task DeletarLivroAsync(ClassesBasicas.Livro.LivroBC l) {
            return base.Channel.DeletarLivroAsync(l);
        }
        
        public void CadastrarUsuario(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.CadastrarUsuario(u);
        }
        
        public System.Threading.Tasks.Task CadastrarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.CadastrarUsuarioAsync(u);
        }
        
        public void AlterarUsuario(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.AlterarUsuario(u);
        }
        
        public System.Threading.Tasks.Task AlterarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.AlterarUsuarioAsync(u);
        }
        
        public ClassesBasicas.Usuario.UsuarioBC[] ListarUsuario(ClassesBasicas.Usuario.UsuarioBC filtro) {
            return base.Channel.ListarUsuario(filtro);
        }
        
        public System.Threading.Tasks.Task<ClassesBasicas.Usuario.UsuarioBC[]> ListarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC filtro) {
            return base.Channel.ListarUsuarioAsync(filtro);
        }
        
        public void DeletarUsuario(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.DeletarUsuario(u);
        }
        
        public System.Threading.Tasks.Task DeletarUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.DeletarUsuarioAsync(u);
        }
        
        public void CadastrarAluguel(ClassesBasicas.Aluguel.AluguelBC a) {
            base.Channel.CadastrarAluguel(a);
        }
        
        public System.Threading.Tasks.Task CadastrarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC a) {
            return base.Channel.CadastrarAluguelAsync(a);
        }
        
        public void AlterarAluguel(ClassesBasicas.Aluguel.AluguelBC a) {
            base.Channel.AlterarAluguel(a);
        }
        
        public System.Threading.Tasks.Task AlterarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC a) {
            return base.Channel.AlterarAluguelAsync(a);
        }
        
        public ClassesBasicas.Aluguel.AluguelBC[] ListarAluguel(ClassesBasicas.Aluguel.AluguelBC filtro) {
            return base.Channel.ListarAluguel(filtro);
        }
        
        public System.Threading.Tasks.Task<ClassesBasicas.Aluguel.AluguelBC[]> ListarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC filtro) {
            return base.Channel.ListarAluguelAsync(filtro);
        }
        
        public void DeltetarAluguel(ClassesBasicas.Aluguel.AluguelBC a) {
            base.Channel.DeltetarAluguel(a);
        }
        
        public System.Threading.Tasks.Task DeltetarAluguelAsync(ClassesBasicas.Aluguel.AluguelBC a) {
            return base.Channel.DeltetarAluguelAsync(a);
        }
        
        public void CadastrarPagamento(ClassesBasicas.Pagamento.PagamentoBC p) {
            base.Channel.CadastrarPagamento(p);
        }
        
        public System.Threading.Tasks.Task CadastrarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC p) {
            return base.Channel.CadastrarPagamentoAsync(p);
        }
        
        public void AlterarPagamento(ClassesBasicas.Pagamento.PagamentoBC p) {
            base.Channel.AlterarPagamento(p);
        }
        
        public System.Threading.Tasks.Task AlterarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC p) {
            return base.Channel.AlterarPagamentoAsync(p);
        }
        
        public ClassesBasicas.Pagamento.PagamentoBC[] ListarPagamento(ClassesBasicas.Pagamento.PagamentoBC filtro) {
            return base.Channel.ListarPagamento(filtro);
        }
        
        public System.Threading.Tasks.Task<ClassesBasicas.Pagamento.PagamentoBC[]> ListarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC filtro) {
            return base.Channel.ListarPagamentoAsync(filtro);
        }
        
        public void DeletarPagamento(ClassesBasicas.Pagamento.PagamentoBC p) {
            base.Channel.DeletarPagamento(p);
        }
        
        public System.Threading.Tasks.Task DeletarPagamentoAsync(ClassesBasicas.Pagamento.PagamentoBC p) {
            return base.Channel.DeletarPagamentoAsync(p);
        }
        
        public void LancarMulta(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.LancarMulta(u);
        }
        
        public System.Threading.Tasks.Task LancarMultaAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.LancarMultaAsync(u);
        }
        
        public void BaixaMulta(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.BaixaMulta(u);
        }
        
        public System.Threading.Tasks.Task BaixaMultaAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.BaixaMultaAsync(u);
        }
        
        public void EmitirNF(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.EmitirNF(u);
        }
        
        public System.Threading.Tasks.Task EmitirNFAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.EmitirNFAsync(u);
        }
        
        public void BloquearUsuario(ClassesBasicas.Usuario.UsuarioBC u) {
            base.Channel.BloquearUsuario(u);
        }
        
        public System.Threading.Tasks.Task BloquearUsuarioAsync(ClassesBasicas.Usuario.UsuarioBC u) {
            return base.Channel.BloquearUsuarioAsync(u);
        }
    }
}
